apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-text-classification
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ai-apis.labels" . | nindent 4 }}
    app.kubernetes.io/component: text-classification
  annotations:
    helm.sh/chart: {{ include "ai-apis.chart" . }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.textClassification.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "ai-apis.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: text-classification
