apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-textclass-cache
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ai-apis.labels" . | nindent 4 }}
    app.kubernetes.io/component: text-classification
  annotations:
    helm.sh/chart: {{ include "ai-apis.chart" . }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.global.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.textClassification.cacheStorage | quote }}
