name: Lint and Type Check

on:
  push:
    branches: [main, develop, claude/**]
  pull_request:
    branches: [main, develop]

jobs:
  lint:
    name: Code Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort ruff mypy
          # Install package dependencies for type checking
          pip install -e ".[dev]"

      - name: Check code formatting with Black
        run: |
          black --check --diff src/ tests/
        continue-on-error: false

      - name: Check import sorting with isort
        run: |
          isort --check-only --diff src/ tests/
        continue-on-error: false

      - name: Lint with Ruff
        run: |
          ruff check src/ tests/
        continue-on-error: false

      - name: Type check with MyPy
        run: |
          mypy src/
        continue-on-error: true  # Type checking can be strict, so just warn for now

      - name: Check for security issues with Ruff
        run: |
          ruff check --select S src/
        continue-on-error: true
